"""
n5_curriculum.py — Source-of-truth content for the N5 course.

This is NOT loaded at runtime. It's the authoring file: running
`python lessons/build_curriculum.py` reads CURRICULUM below and emits
fully-formed, validated lesson JSON into lessons/data/.

Each lesson entry carries the *teaching* content (objectives, study_guide,
examples, grammar_note, culture_note) plus vocab. Exercises are generated
automatically from vocab + patterns so every lesson reliably contains all
eight exercise types without hand-writing hundreds of JSON blocks.
"""

# Each vocab item: (ja, reading, romaji, en)  — reading == ja when already kana
# Each lesson: dict with teaching fields + vocab + optional sentences[]
# sentences: (ja, romaji, en) used for build/translate/listen exercises.

CURRICULUM = [
 # ---- Lessons 1-5 already exist as standalone JSON (greetings/numbers/food/
 #      travel/family). The generator starts at order 6 and continues. ----

 {
  "id": "self_intro", "order": 6, "title": "Self-Introduction", "icon": "🙋",
  "difficulty": 1,
  "description": "Introduce yourself: name, country, and 'I am ___'.",
  "objectives": [
    "Use the X は Y です sentence pattern",
    "Say your name and where you're from",
    "Ask someone's name politely"],
  "study_guide": [
    {"heading": "The most important pattern: X は Y です",
     "body": "Japanese sentences often follow [topic] は [info] です. は here is a particle pronounced 'wa' (not 'ha'). です (desu) is a polite 'is/am/are'. わたしは リサです = I am Lisa. Literally: 'As for me, Lisa is.'"},
    {"heading": "Particle は = 'as for'",
     "body": "は marks the topic — the thing you're talking about. わたしは… = 'as for me…'. You'll see this particle everywhere; mastering it now makes everything later easier."},
    {"heading": "Asking back",
     "body": "Add か to make a question: おなまえは なんですか = What is your name? No question mark needed in Japanese — か does that job."}],
  "examples": [
    ("わたしは がくせいです。", "watashi wa gakusei desu", "I am a student."),
    ("わたしは アメリカじんです。", "watashi wa amerika-jin desu", "I am American."),
    ("おなまえは なんですか。", "o-namae wa nan desu ka", "What is your name?"),
    ("どうぞ よろしく。", "douzo yoroshiku", "Pleased to meet you.")],
  "grammar_note": {"title": "は (wa) and です",
    "body": "は marks the topic and is read 'wa'. です makes the sentence polite. To ask, append か. To say 'is not', です becomes じゃ ありません (covered later)."},
  "culture_note": "When introducing yourself, end with どうぞ よろしく おねがいします and a bow. It roughly means 'please be kind to me' — there's no English equivalent, but it's essential social glue.",
  "vocab": [
    ("私","わたし","watashi","I / me"),
    ("名前","なまえ","namae","name"),
    ("学生","がくせい","gakusei","student"),
    ("先生","せんせい","sensei","teacher"),
    ("会社員","かいしゃいん","kaishain","office worker"),
    ("アメリカ人","アメリカじん","amerika-jin","American (person)"),
    ("日本人","にほんじん","nihon-jin","Japanese (person)"),
    ("何","なに","nani","what"),
    ("はい","はい","hai","yes"),
    ("いいえ","いいえ","iie","no")],
  "sentences": [
    ("わたしは がくせいです。","watashi wa gakusei desu","I am a student."),
    ("わたしは にほんじんです。","watashi wa nihon-jin desu","I am Japanese."),
    ("あなたは せんせいですか。","anata wa sensei desu ka","Are you a teacher?")],
 },

 {
  "id": "this_that", "order": 7, "title": "This & That (これ・それ・あれ)",
  "icon": "👉", "difficulty": 1,
  "description": "Point at things and name them with これ, それ, あれ.",
  "objectives": [
    "Distinguish これ / それ / あれ by distance",
    "Ask 'what is this?' これは なんですか",
    "Use の to connect nouns (this is my book)"],
  "study_guide": [
    {"heading": "Three distances",
     "body": "これ = this (near me). それ = that (near you). あれ = that over there (far from both). The ko-so-a-do system runs through all of Japanese — learn it once, reuse forever."},
    {"heading": "これは なんですか",
     "body": "これは なんですか = What is this? Answer: それは ほんです = That (by you) is a book. Notice the speaker switches これ→それ depending on who's closer."},
    {"heading": "の joins nouns",
     "body": "の links two nouns, usually showing possession or type: わたしの ほん = my book, にほんごの ほん = a Japanese-language book."}],
  "examples": [
    ("これは ほんです。", "kore wa hon desu", "This is a book."),
    ("それは なんですか。", "sore wa nan desu ka", "What is that?"),
    ("あれは わたしの かばんです。", "are wa watashi no kaban desu", "That over there is my bag."),
    ("これは にほんごの ほんです。", "kore wa nihongo no hon desu", "This is a Japanese book.")],
  "grammar_note": {"title": "これ・それ・あれ + の",
    "body": "これ/それ/あれ are 'this/that/that-yonder'. Pair them with は…です to identify things. の connects nouns: A の B means 'B of A' or 'A's B'."},
  "culture_note": "Pointing with one finger is a little blunt in Japan; people often gesture with an open hand. But これ/それ/あれ in speech do the pointing for you.",
  "vocab": [
    ("これ","これ","kore","this (near me)"),
    ("それ","それ","sore","that (near you)"),
    ("あれ","あれ","are","that (over there)"),
    ("本","ほん","hon","book"),
    ("鞄","かばん","kaban","bag"),
    ("時計","とけい","tokei","clock / watch"),
    ("傘","かさ","kasa","umbrella"),
    ("ペン","ペン","pen","pen"),
    ("日本語","にほんご","nihongo","Japanese (language)"),
    ("英語","えいご","eigo","English (language)")],
  "sentences": [
    ("これは ペンです。","kore wa pen desu","This is a pen."),
    ("それは わたしの かさです。","sore wa watashi no kasa desu","That is my umbrella."),
    ("あれは とけいです。","are wa tokei desu","That over there is a clock.")],
 },

 {
  "id": "days_time", "order": 8, "title": "Days & Time", "icon": "🕐",
  "difficulty": 2,
  "description": "Tell the time, name the days of the week, and say 'when'.",
  "objectives": [
    "Read clock times with じ (o'clock) and ふん (minutes)",
    "Name the seven days of the week",
    "Ask なんじですか (what time is it?)"],
  "study_guide": [
    {"heading": "Telling the hour: 〜じ",
     "body": "Add じ to a number for the hour: いちじ = 1 o'clock, さんじ = 3 o'clock. Watch the irregulars: 4 o'clock is よじ (not よんじ), 7 is しちじ, 9 is くじ."},
    {"heading": "Minutes: 〜ふん / 〜ぷん",
     "body": "Minutes use ふん or ぷん depending on the number: ごふん = 5 min, じゅっぷん = 10 min. ごぜん = AM, ごご = PM. ごご さんじ = 3 PM."},
    {"heading": "Days of the week",
     "body": "Each day ends in ようび: げつようび (Mon), かようび (Tue), すいようび (Wed), もくようび (Thu), きんようび (Fri), どようび (Sat), にちようび (Sun)."}],
  "examples": [
    ("いま なんじですか。", "ima nan-ji desu ka", "What time is it now?"),
    ("ごご さんじです。", "gogo san-ji desu", "It's 3 PM."),
    ("きょうは げつようびです。", "kyou wa getsu-youbi desu", "Today is Monday."),
    ("しけんは きんようびです。", "shiken wa kin-youbi desu", "The exam is on Friday.")],
  "grammar_note": {"title": "Time expressions",
    "body": "Hour = number + じ (irregulars: 4=よ, 7=しち, 9=く). Minutes = number + ふん/ぷん. ごぜん=AM, ごご=PM. Days end in ようび."},
  "culture_note": "Japanese trains and shops run on precise time. A meeting at さんじ means 3:00 sharp — arriving 'on time' culturally means arriving a few minutes early.",
  "vocab": [
    ("今","いま","ima","now"),
    ("時","じ","ji","o'clock (hour)"),
    ("分","ふん","fun","minute(s)"),
    ("午前","ごぜん","gozen","AM / morning"),
    ("午後","ごご","gogo","PM / afternoon"),
    ("月曜日","げつようび","getsu-youbi","Monday"),
    ("金曜日","きんようび","kin-youbi","Friday"),
    ("土曜日","どようび","do-youbi","Saturday"),
    ("日曜日","にちようび","nichi-youbi","Sunday"),
    ("今日","きょう","kyou","today")],
  "sentences": [
    ("いま くじです。","ima ku-ji desu","It is 9 o'clock now."),
    ("きょうは どようびです。","kyou wa do-youbi desu","Today is Saturday."),
    ("ごぜん しちじです。","gozen shichi-ji desu","It is 7 AM.")],
 },

 {
  "id": "verbs_present", "order": 9, "title": "Daily Verbs (ます form)", "icon": "🏃",
  "difficulty": 2,
  "description": "Talk about what you do: eat, drink, go, see, using polite ます verbs.",
  "objectives": ["Use the polite ます verb form","Build [object] を [verb] sentences","Negate with ません"],
  "study_guide": [
    {"heading":"The ます form is your safe default","body":"Polite present verbs end in ます: たべます (eat), のみます (drink), いきます (go), みます (see/watch). Use ます forms everywhere as a beginner — they're always polite and always correct."},
    {"heading":"Negative = ません","body":"Swap ます for ません to make it negative: たべます (I eat) → たべません (I don't eat). にくを たべません = I don't eat meat."},
    {"heading":"Word order: verb goes last","body":"Japanese is Subject–Object–Verb. わたしは ごはんを たべます = I rice eat. The verb always comes at the very end of the sentence."}],
  "examples": [
    ("まいにち コーヒーを のみます。","mainichi koohii o nomimasu","I drink coffee every day."),
    ("テレビを みます。","terebi o mimasu","I watch TV."),
    ("にくを たべません。","niku o tabemasen","I don't eat meat."),
    ("がっこうへ いきます。","gakkou e ikimasu","I go to school.")],
  "grammar_note": {"title":"ます / ません","body":"Polite verbs end in ます (affirmative) or ません (negative). The object takes を. Destination takes へ or に."},
  "culture_note":"Using ます forms shows respect and is expected with anyone you don't know well. Casual 'dictionary form' comes later — start polite and you'll never offend.",
  "vocab": [
    ("食べます","たべます","tabemasu","to eat"),
    ("飲みます","のみます","nomimasu","to drink"),
    ("行きます","いきます","ikimasu","to go"),
    ("見ます","みます","mimasu","to see / watch"),
    ("読みます","よみます","yomimasu","to read"),
    ("書きます","かきます","kakimasu","to write"),
    ("聞きます","ききます","kikimasu","to listen / ask"),
    ("します","します","shimasu","to do"),
    ("毎日","まいにち","mainichi","every day"),
    ("学校","がっこう","gakkou","school")],
  "sentences": [
    ("ほんを よみます。","hon o yomimasu","I read a book."),
    ("おんがくを ききます。","ongaku o kikimasu","I listen to music."),
    ("にくを たべません。","niku o tabemasen","I don't eat meat.")],
 },
 {
  "id": "places_locations", "order": 10, "title": "Places & Locations", "icon": "🗺️",
  "difficulty": 2,
  "description": "Say where things are with あります／います and location words.",
  "objectives": ["Use あります (things) vs います (living)","Place words: うえ, した, なか, となり","Ask どこに ありますか"],
  "study_guide": [
    {"heading":"あります vs います","body":"あります = exists (for things/plants). います = exists (for people/animals). ねこが います = there is a cat. ほんが あります = there is a book."},
    {"heading":"Location with に","body":"Use に to mark where: つくえの うえに ほんが あります = on the desk there is a book. Position words: うえ(on), した(under), なか(inside), となり(next to), まえ(front), うしろ(behind)."},
    {"heading":"Asking where","body":"〜は どこに ありますか / いますか = where is ~? えきは どこに ありますか = Where is the station?"}],
  "examples": [
    ("つくえの うえに ペンが あります。","tsukue no ue ni pen ga arimasu","There's a pen on the desk."),
    ("いえの なかに ねこが います。","ie no naka ni neko ga imasu","There's a cat inside the house."),
    ("ぎんこうは どこに ありますか。","ginkou wa doko ni arimasu ka","Where is the bank?"),
    ("えきの となりに あります。","eki no tonari ni arimasu","It's next to the station.")],
  "grammar_note": {"title":"あります・います + に","body":"あります for inanimate, います for animate. Location marked by に. Existence subject marked by が."},
  "culture_note":"Convenience stores (コンビニ) are everywhere in Japan and a traveler's best friend — open 24/7 for food, ATMs, tickets, and clean restrooms.",
  "vocab": [
    ("あります","あります","arimasu","to exist (things)"),
    ("います","います","imasu","to exist (living)"),
    ("上","うえ","ue","on / above"),
    ("下","した","shita","under / below"),
    ("中","なか","naka","inside"),
    ("隣","となり","tonari","next to"),
    ("銀行","ぎんこう","ginkou","bank"),
    ("家","いえ","ie","house / home"),
    ("机","つくえ","tsukue","desk"),
    ("猫","ねこ","neko","cat")],
  "sentences": [
    ("つくえの うえに ほんが あります。","tsukue no ue ni hon ga arimasu","There is a book on the desk."),
    ("いえに ねこが います。","ie ni neko ga imasu","There is a cat at home."),
    ("ぎんこうは どこに ありますか。","ginkou wa doko ni arimasu ka","Where is the bank?")],
 },
 {
  "id": "adjectives_i", "order": 11, "title": "い-Adjectives", "icon": "🌶️",
  "difficulty": 2,
  "description": "Describe things: big, small, hot, delicious — with い-adjectives.",
  "objectives": ["Use い-adjectives before nouns and with です","Negate い-adjectives (〜くない)","Combine adjective + noun"],
  "study_guide": [
    {"heading":"い-adjectives end in い","body":"おおきい (big), ちいさい (small), あつい (hot), さむい (cold), たかい (expensive/tall). Put them straight before a noun: おおきい いえ = a big house."},
    {"heading":"With です","body":"このいえは おおきいです = This house is big. Keep the い; just add です for politeness. Don't add な."},
    {"heading":"Negative: 〜くない","body":"Drop い, add くない: たかい → たかくない (not expensive). Polite: たかくないです or たかく ありません."}],
  "examples": [
    ("このカメラは たかいです。","kono kamera wa takai desu","This camera is expensive."),
    ("あたらしい くるまですね。","atarashii kuruma desu ne","That's a new car, isn't it."),
    ("きょうは さむくないです。","kyou wa samukunai desu","Today isn't cold."),
    ("おおきい いぬが すきです。","ookii inu ga suki desu","I like big dogs.")],
  "grammar_note": {"title":"い-adjective conjugation","body":"Attributive: adj + noun. Predicate: adj + です. Negative: drop い + くないです. Past comes later (〜かったです)."},
  "culture_note":"かわいい (cute) is one of the most-used words in Japan, applied to everything from babies to bullet trains. Don't be surprised how often you hear it.",
  "vocab": [
    ("大きい","おおきい","ookii","big"),
    ("小さい","ちいさい","chiisai","small"),
    ("暑い","あつい","atsui","hot (weather)"),
    ("寒い","さむい","samui","cold (weather)"),
    ("高い","たかい","takai","expensive / tall"),
    ("安い","やすい","yasui","cheap"),
    ("新しい","あたらしい","atarashii","new"),
    ("古い","ふるい","furui","old"),
    ("面白い","おもしろい","omoshiroi","interesting / fun"),
    ("可愛い","かわいい","kawaii","cute")],
  "sentences": [
    ("このいえは おおきいです。","kono ie wa ookii desu","This house is big."),
    ("きょうは さむいです。","kyou wa samui desu","Today is cold."),
    ("やすい みせですね。","yasui mise desu ne","It's a cheap shop, isn't it.")],
 },
 {
  "id": "adjectives_na", "order": 12, "title": "な-Adjectives", "icon": "✨",
  "difficulty": 2,
  "description": "More describing words: pretty, quiet, famous — the な type.",
  "objectives": ["Use な-adjectives with な before nouns","Predicate form with です","Tell い- and な-adjectives apart"],
  "study_guide": [
    {"heading":"な-adjectives take な before a noun","body":"きれいな はな = a pretty flower, しずかな へや = a quiet room. The な appears only when the adjective sits directly before a noun."},
    {"heading":"With です, no な","body":"このへやは しずかです = This room is quiet. No な before です. The な is only the 'glue' to a following noun."},
    {"heading":"Spotting the type","body":"Most adjectives ending in い are い-type, BUT きれい and ゆうめい end in い yet are な-type. Learn those two as exceptions."}],
  "examples": [
    ("しずかな まちです。","shizuka na machi desu","It's a quiet town."),
    ("このはなは きれいです。","kono hana wa kirei desu","This flower is pretty."),
    ("ゆうめいな せんせいです。","yuumei na sensei desu","She's a famous teacher."),
    ("にほんごは べんりな ことばです。","nihongo wa benri na kotoba desu","Japanese is a handy language.")],
  "grammar_note": {"title":"な-adjective usage","body":"Before a noun: adj + な + noun. Predicate: adj + です (no な). Negative: adj + じゃ ありません."},
  "culture_note":"げんき (energetic/well) doubles as 'how are you': おげんきですか. It's a な-adjective and one of the warmest everyday words.",
  "vocab": [
    ("綺麗","きれい","kirei","pretty / clean"),
    ("静か","しずか","shizuka","quiet"),
    ("賑やか","にぎやか","nigiyaka","lively"),
    ("有名","ゆうめい","yuumei","famous"),
    ("便利","べんり","benri","convenient"),
    ("元気","げんき","genki","healthy / energetic"),
    ("親切","しんせつ","shinsetsu","kind"),
    ("好き","すき","suki","liked / favorite"),
    ("嫌い","きらい","kirai","disliked"),
    ("上手","じょうず","jouzu","skillful / good at")],
  "sentences": [
    ("しずかな へやです。","shizuka na heya desu","It is a quiet room."),
    ("このまちは にぎやかです。","kono machi wa nigiyaka desu","This town is lively."),
    ("しんせつな ひとですね。","shinsetsu na hito desu ne","She is a kind person, isn't she.")],
 },
 {
  "id": "shopping", "order": 13, "title": "Shopping", "icon": "🛍️",
  "difficulty": 2,
  "description": "Buy things, ask prices, and use counters in a shop.",
  "objectives": ["Ask いくらですか and これを ください","Use 〜を ください to request","Recognize price/counter words"],
  "study_guide": [
    {"heading":"〜を ください","body":"これを ください = I'll take this / please give me this. Point + これ/それ + を ください is all you need to shop."},
    {"heading":"Asking the price","body":"いくらですか = how much? ぜんぶで いくらですか = how much in total? Numbers + えん = yen: ごひゃくえん = 500 yen."},
    {"heading":"Counters preview","body":"Japanese counts objects with counter words: ひとつ, ふたつ, みっつ (1,2,3 generic things). りんごを ふたつ ください = two apples please."}],
  "examples": [
    ("これを ください。","kore o kudasai","I'll take this, please."),
    ("ぜんぶで いくらですか。","zenbu de ikura desu ka","How much altogether?"),
    ("みずを ふたつ ください。","mizu o futatsu kudasai","Two waters, please."),
    ("カードで おねがいします。","kaado de onegai shimasu","By card, please.")],
  "grammar_note": {"title":"〜を ください / で","body":"〜を ください requests an item. で marks the means (カードで = by card). Generic counters: ひとつ/ふたつ/みっつ…"},
  "culture_note":"Cash is still king in many Japanese shops, and you'll often place money on a small tray rather than into the cashier's hand. IC cards (Suica/Pasmo) are the easy modern option.",
  "vocab": [
    ("店","みせ","mise","shop / store"),
    ("買います","かいます","kaimasu","to buy"),
    ("円","えん","en","yen"),
    ("一つ","ひとつ","hitotsu","one (thing)"),
    ("二つ","ふたつ","futatsu","two (things)"),
    ("三つ","みっつ","mittsu","three (things)"),
    ("全部","ぜんぶ","zenbu","all / total"),
    ("カード","カード","kaado","card"),
    ("お金","おかね","okane","money"),
    ("レジ","レジ","reji","cash register")],
  "sentences": [
    ("これを ください。","kore o kudasai","I'll take this."),
    ("ぜんぶで いくらですか。","zenbu de ikura desu ka","How much in total?"),
    ("りんごを ふたつ かいます。","ringo o futatsu kaimasu","I buy two apples.")],
 },
 {
  "id": "weather_seasons", "order": 14, "title": "Weather & Seasons", "icon": "🌦️",
  "difficulty": 2,
  "description": "Talk about the weather and the four seasons.",
  "objectives": ["Describe weather with い-adjectives","Name the four seasons","Use 〜ね for agreement"],
  "study_guide": [
    {"heading":"Weather basics","body":"てんき = weather. いい てんき = good weather. あめ = rain, ゆき = snow, はれ = clear, くもり = cloudy. きょうは あめです = It's rainy today."},
    {"heading":"The four seasons","body":"はる (spring), なつ (summer), あき (autumn), ふゆ (winter). なつは あついです = Summer is hot."},
    {"heading":"〜ね for shared feeling","body":"End with ね to invite agreement: いい てんきですね = Nice weather, isn't it? It's friendly and very common."}],
  "examples": [
    ("きょうは あめです。","kyou wa ame desu","It's raining today."),
    ("なつは とても あついです。","natsu wa totemo atsui desu","Summer is very hot."),
    ("はるは あたたかいですね。","haru wa atatakai desu ne","Spring is warm, isn't it."),
    ("ふゆは ゆきが ふります。","fuyu wa yuki ga furimasu","In winter it snows.")],
  "grammar_note": {"title":"Weather + ね","body":"Weather nouns + です describe conditions. とても = very. ね seeks agreement and softens the statement."},
  "culture_note":"Cherry blossoms (さくら) in spring are a national event — people picnic under the trees (おはなみ). Each season has its own foods, festivals, and greetings.",
  "vocab": [
    ("天気","てんき","tenki","weather"),
    ("雨","あめ","ame","rain"),
    ("雪","ゆき","yuki","snow"),
    ("晴れ","はれ","hare","clear / sunny"),
    ("春","はる","haru","spring"),
    ("夏","なつ","natsu","summer"),
    ("秋","あき","aki","autumn"),
    ("冬","ふゆ","fuyu","winter"),
    ("暖かい","あたたかい","atatakai","warm"),
    ("涼しい","すずしい","suzushii","cool")],
  "sentences": [
    ("きょうは はれです。","kyou wa hare desu","It is sunny today."),
    ("なつは あついです。","natsu wa atsui desu","Summer is hot."),
    ("いい てんきですね。","ii tenki desu ne","Nice weather, isn't it.")],
 },
 {
  "id": "hobbies", "order": 15, "title": "Hobbies & Likes", "icon": "🎨",
  "difficulty": 2,
  "description": "Say what you like and what you're good at with すき and じょうず.",
  "objectives": ["Use 〜が すきです (I like ~)","Use 〜が じょうずです (good at ~)","Talk about hobbies (しゅみ)"],
  "study_guide": [
    {"heading":"〜が すきです","body":"The thing you like takes が, not を: おんがくが すきです = I like music. すき is a な-adjective meaning 'liked'."},
    {"heading":"Degrees of liking","body":"だいすき = love, すき = like, あまり すきじゃない = don't really like, きらい = dislike. スポーツが だいすきです = I love sports."},
    {"heading":"じょうず / へた","body":"じょうず = good at, へた = bad at, both take が: りょうりが じょうずです = good at cooking."}],
  "examples": [
    ("わたしは えいがが すきです。","watashi wa eiga ga suki desu","I like movies."),
    ("りょうりが じょうずですね。","ryouri ga jouzu desu ne","You're good at cooking!"),
    ("スポーツが だいすきです。","supootsu ga daisuki desu","I love sports."),
    ("しゅみは おんがくです。","shumi wa ongaku desu","My hobby is music.")],
  "grammar_note": {"title":"が with feelings/skill","body":"すき・きらい・じょうず・へた describe feeling/ability and mark their object with が, not を."},
  "culture_note":"Asking しゅみは なんですか (what's your hobby?) is a standard friendly ice-breaker, much like 'what do you do for fun?' in English.",
  "vocab": [
    ("趣味","しゅみ","shumi","hobby"),
    ("映画","えいが","eiga","movie"),
    ("音楽","おんがく","ongaku","music"),
    ("スポーツ","スポーツ","supootsu","sport(s)"),
    ("料理","りょうり","ryouri","cooking / cuisine"),
    ("旅行","りょこう","ryokou","travel"),
    ("大好き","だいすき","daisuki","love / really like"),
    ("下手","へた","heta","bad at"),
    ("ゲーム","ゲーム","geemu","game"),
    ("読書","どくしょ","dokusho","reading")],
  "sentences": [
    ("えいがが すきです。","eiga ga suki desu","I like movies."),
    ("りょうりが じょうずです。","ryouri ga jouzu desu","I'm good at cooking."),
    ("しゅみは りょこうです。","shumi wa ryokou desu","My hobby is travel.")],
 },

 {
  "id": "verbs_past", "order": 16, "title": "Past Tense (ました)", "icon": "⏪",
  "difficulty": 3,
  "description": "Talk about yesterday: the polite past ました / ませんでした.",
  "objectives": ["Form polite past with ました","Negative past ませんでした","Use time words きのう, せんしゅう"],
  "study_guide": [
    {"heading":"ます → ました","body":"For polite past, swap ます for ました: たべます → たべました (ate). きのう すしを たべました = I ate sushi yesterday."},
    {"heading":"Negative past: ませんでした","body":"たべます → たべませんでした (did not eat). きのう べんきょうしませんでした = I didn't study yesterday."},
    {"heading":"Time words","body":"きのう (yesterday), せんしゅう (last week), せんげつ (last month), きょねん (last year) usually go near the start of the sentence."}],
  "examples": [
    ("きのう えいがを みました。","kinou eiga o mimashita","I watched a movie yesterday."),
    ("せんしゅう きょうとへ いきました。","senshuu kyouto e ikimashita","I went to Kyoto last week."),
    ("あさごはんを たべませんでした。","asagohan o tabemasen deshita","I didn't eat breakfast."),
    ("テストは どうでしたか。","tesuto wa dou deshita ka","How was the test?")],
  "grammar_note": {"title":"ました / ませんでした","body":"Past affirmative = stem + ました. Past negative = stem + ませんでした. です past = でした."},
  "culture_note":"おつかれさまでした ('you must be tired', i.e. good work) is said at the end of a workday or shared effort — a past-tense set phrase you'll hear daily.",
  "vocab": [
    ("昨日","きのう","kinou","yesterday"),
    ("先週","せんしゅう","senshuu","last week"),
    ("先月","せんげつ","sengetsu","last month"),
    ("去年","きょねん","kyonen","last year"),
    ("勉強します","べんきょうします","benkyou shimasu","to study"),
    ("会います","あいます","aimasu","to meet"),
    ("来ます","きます","kimasu","to come"),
    ("帰ります","かえります","kaerimasu","to return home"),
    ("朝ご飯","あさごはん","asagohan","breakfast"),
    ("テスト","テスト","tesuto","test")],
  "sentences": [
    ("きのう えいがを みました。","kinou eiga o mimashita","I watched a movie yesterday."),
    ("あさごはんを たべませんでした。","asagohan o tabemasen deshita","I didn't eat breakfast."),
    ("せんしゅう ともだちに あいました。","senshuu tomodachi ni aimashita","I met a friend last week.")],
 },
 {
  "id": "te_form", "order": 17, "title": "The て-Form & Requests", "icon": "🔗",
  "difficulty": 3,
  "description": "The versatile て-form: make polite requests and link actions.",
  "objectives": ["Recognize the て-form of common verbs","Make requests with 〜てください","Link actions: 〜て、〜ます"],
  "study_guide": [
    {"heading":"What the て-form does","body":"The て-form is a connector. It builds requests (〜てください), ongoing actions (〜ています), permission, and links clauses. It's the gateway to intermediate Japanese."},
    {"heading":"〜てください = please do","body":"みてください = please look, きいてください = please listen, まってください = please wait. Soft, polite, essential in class and travel."},
    {"heading":"Linking with て","body":"おきて、ごはんを たべて、がっこうへ いきます = I get up, eat, and go to school. て chains actions in order."}],
  "examples": [
    ("ちょっと まってください。","chotto matte kudasai","Please wait a moment."),
    ("ここに なまえを かいてください。","koko ni namae o kaite kudasai","Please write your name here."),
    ("もういちど いってください。","mou ichido itte kudasai","Please say it once more."),
    ("おきて、コーヒーを のみます。","okite, koohii o nomimasu","I get up and drink coffee.")],
  "grammar_note": {"title":"て-form + ください","body":"て-form + ください = polite request. て also links sequential actions and forms the basis of many grammar patterns to come."},
  "culture_note":"ちょっと まって ('wait a sec') softened with ください is everywhere. Adding ちょっと (a little) makes requests gentler and more natural.",
  "vocab": [
    ("待ちます","まちます","machimasu","to wait"),
    ("使います","つかいます","tsukaimasu","to use"),
    ("起きます","おきます","okimasu","to wake up"),
    ("寝ます","ねます","nemasu","to sleep"),
    ("言います","いいます","iimasu","to say"),
    ("座ります","すわります","suwarimasu","to sit"),
    ("立ちます","たちます","tachimasu","to stand"),
    ("もう一度","もういちど","mou ichido","once more"),
    ("ちょっと","ちょっと","chotto","a little / a moment"),
    ("ここ","ここ","koko","here")],
  "sentences": [
    ("ちょっと まってください。","chotto matte kudasai","Please wait a moment."),
    ("なまえを かいてください。","namae o kaite kudasai","Please write your name."),
    ("もういちど いってください。","mou ichido itte kudasai","Please say it again.")],
 },
 {
  "id": "te_imasu", "order": 18, "title": "Now Happening (ています)", "icon": "📲",
  "difficulty": 3,
  "description": "Describe actions in progress and ongoing states with ています.",
  "objectives": ["Form 〜ています for ongoing actions","Describe states (married, living in ~)","Answer なにを していますか"],
  "study_guide": [
    {"heading":"〜ています = -ing","body":"て-form + います = action in progress: たべています = (I) am eating. いま なにを していますか = What are you doing now?"},
    {"heading":"Ongoing states","body":"Some verbs become states: とうきょうに すんでいます = I live in Tokyo. けっこんしています = I'm married. しっています = I know."},
    {"heading":"Talking about jobs","body":"ぎんこうで はたらいています = I work at a bank. で marks where an action happens."}],
  "examples": [
    ("いま ごはんを たべています。","ima gohan o tabete imasu","I'm eating now."),
    ("とうきょうに すんでいます。","toukyou ni sunde imasu","I live in Tokyo."),
    ("かいしゃで はたらいています。","kaisha de hataraite imasu","I work at a company."),
    ("なにを していますか。","nani o shite imasu ka","What are you doing?")],
  "grammar_note": {"title":"て-form + います","body":"Expresses ongoing action or resulting state. で marks the place of an action; に marks the place of residence/existence."},
  "culture_note":"Asking おしごとは？ ('your work?') is normal small talk, but Japanese people often answer modestly. Workplace identity matters socially in Japan.",
  "vocab": [
    ("住みます","すみます","sumimasu","to live / reside"),
    ("働きます","はたらきます","hatarakimasu","to work"),
    ("結婚します","けっこんします","kekkon shimasu","to marry"),
    ("知ります","しります","shirimasu","to know"),
    ("会社","かいしゃ","kaisha","company"),
    ("仕事","しごと","shigoto","job / work"),
    ("作ります","つくります","tsukurimasu","to make"),
    ("遊びます","あそびます","asobimasu","to play / hang out"),
    ("歩きます","あるきます","arukimasu","to walk"),
    ("走ります","はしります","hashirimasu","to run")],
  "sentences": [
    ("いま たべています。","ima tabete imasu","I am eating now."),
    ("とうきょうに すんでいます。","toukyou ni sunde imasu","I live in Tokyo."),
    ("かいしゃで はたらいています。","kaisha de hataraite imasu","I work at a company.")],
 },
 {
  "id": "want_desire", "order": 19, "title": "Wants & Wishes (〜たい)", "icon": "🌟",
  "difficulty": 3,
  "description": "Say what you want to do and what you want with 〜たい and ほしい.",
  "objectives": ["Form 〜たいです (want to do)","Use ほしい (want a thing)","Invite with 〜ませんか"],
  "study_guide": [
    {"heading":"〜たいです = want to do","body":"Drop ます, add たいです: たべます → たべたいです (want to eat). にほんへ いきたいです = I want to go to Japan."},
    {"heading":"ほしい = want a thing","body":"For wanting an object, use ほしい: あたらしい くるまが ほしいです = I want a new car. The wanted thing takes が."},
    {"heading":"Inviting: 〜ませんか","body":"いっしょに いきませんか = Won't you go together (with me)? A polite, warm invitation pattern."}],
  "examples": [
    ("にほんへ いきたいです。","nihon e ikitai desu","I want to go to Japan."),
    ("みずが のみたいです。","mizu ga nomitai desu","I want to drink water."),
    ("いっしょに たべませんか。","issho ni tabemasen ka","Shall we eat together?"),
    ("やすみが ほしいです。","yasumi ga hoshii desu","I want a day off.")],
  "grammar_note": {"title":"〜たい / ほしい / ませんか","body":"Verb stem + たいです = want to (verb). Noun + が ほしいです = want (noun). 〜ませんか invites."},
  "culture_note":"Directly saying 'I want' can feel strong; Japanese softens it with ね or context. With friends it's fine — politeness scales with the relationship.",
  "vocab": [
    ("一緒に","いっしょに","issho ni","together"),
    ("休み","やすみ","yasumi","rest / day off / vacation"),
    ("欲しい","ほしい","hoshii","want (a thing)"),
    ("飲み物","のみもの","nomimono","drink / beverage"),
    ("食べ物","たべもの","tabemono","food"),
    ("車","くるま","kuruma","car"),
    ("写真","しゃしん","shashin","photo"),
    ("撮ります","とります","torimasu","to take (a photo)"),
    ("買い物","かいもの","kaimono","shopping"),
    ("時間","じかん","jikan","time")],
  "sentences": [
    ("にほんへ いきたいです。","nihon e ikitai desu","I want to go to Japan."),
    ("みずが のみたいです。","mizu ga nomitai desu","I want to drink water."),
    ("いっしょに いきませんか。","issho ni ikimasen ka","Shall we go together?")],
 },
 {
  "id": "body_health", "order": 20, "title": "Body & Health", "icon": "🩺",
  "difficulty": 3,
  "description": "Body parts, feeling unwell, and visiting a clinic.",
  "objectives": ["Name common body parts","Say 〜が いたいです (~ hurts)","Basic clinic/pharmacy phrases"],
  "study_guide": [
    {"heading":"〜が いたいです","body":"The hurting part takes が: あたまが いたいです = I have a headache. おなかが いたいです = my stomach hurts."},
    {"heading":"Feeling unwell","body":"きぶんが わるいです = I feel sick. ねつが あります = I have a fever. かぜを ひきました = I caught a cold."},
    {"heading":"At the clinic","body":"びょういん = hospital/clinic, くすり = medicine, いしゃ = doctor. だいじょうぶですか = Are you OK?"}],
  "examples": [
    ("あたまが いたいです。","atama ga itai desu","I have a headache."),
    ("ねつが あります。","netsu ga arimasu","I have a fever."),
    ("くすりを のんでください。","kusuri o nonde kudasai","Please take the medicine."),
    ("だいじょうぶですか。","daijoubu desu ka","Are you all right?")],
  "grammar_note": {"title":"〜が いたい / 〜が あります","body":"Body part + が + いたいです expresses pain. Symptoms like ねつ/かぜ use あります / ひきます."},
  "culture_note":"At a Japanese pharmacy (やっきょく) you can get help for minor issues. Masks are worn widely when sick — out of consideration for others, not just self-protection.",
  "vocab": [
    ("頭","あたま","atama","head"),
    ("お腹","おなか","onaka","stomach / belly"),
    ("目","め","me","eye"),
    ("手","て","te","hand"),
    ("足","あし","ashi","leg / foot"),
    ("痛い","いたい","itai","painful / hurts"),
    ("熱","ねつ","netsu","fever"),
    ("薬","くすり","kusuri","medicine"),
    ("病院","びょういん","byouin","hospital / clinic"),
    ("大丈夫","だいじょうぶ","daijoubu","okay / all right")],
  "sentences": [
    ("あたまが いたいです。","atama ga itai desu","I have a headache."),
    ("ねつが あります。","netsu ga arimasu","I have a fever."),
    ("だいじょうぶですか。","daijoubu desu ka","Are you okay?")],
 },

 {
  "id": "directions", "order": 21, "title": "Asking Directions", "icon": "🧭",
  "difficulty": 3,
  "description": "Find your way: left, right, straight, and 'how do I get to ~?'.",
  "objectives": ["Use みぎ/ひだり/まっすぐ","Ask 〜へ どう いきますか","Understand simple directions"],
  "study_guide": [
    {"heading":"Core direction words","body":"みぎ = right, ひだり = left, まっすぐ = straight, つぎ = next. みぎに まがってください = please turn right."},
    {"heading":"Asking the way","body":"えきへ どう いきますか = How do I get to the station? すみません for 'excuse me' opens the question politely."},
    {"heading":"Landmarks","body":"かど = corner, しんごう = traffic light, こうさてん = intersection. つぎの かどを ひだりに = left at the next corner."}],
  "examples": [
    ("えきへ どう いきますか。","eki e dou ikimasu ka","How do I get to the station?"),
    ("まっすぐ いってください。","massugu itte kudasai","Please go straight."),
    ("つぎの しんごうを みぎに。","tsugi no shingou o migi ni","Right at the next light."),
    ("ここから とおいですか。","koko kara tooi desu ka","Is it far from here?")],
  "grammar_note": {"title":"Directions + に まがる","body":"Direction + に + まがってください = turn (direction). から = from, まで = until/to. へ marks the goal of movement."},
  "culture_note":"People in Japan will often walk you partway to your destination rather than just point. Kobans (police boxes, こうばん) are great for directions too.",
  "vocab": [
    ("右","みぎ","migi","right"),
    ("左","ひだり","hidari","left"),
    ("真っ直ぐ","まっすぐ","massugu","straight"),
    ("次","つぎ","tsugi","next"),
    ("角","かど","kado","corner"),
    ("信号","しんごう","shingou","traffic light"),
    ("曲がります","まがります","magarimasu","to turn"),
    ("遠い","とおい","tooi","far"),
    ("近い","ちかい","chikai","near"),
    ("地図","ちず","chizu","map")],
  "sentences": [
    ("まっすぐ いってください。","massugu itte kudasai","Please go straight."),
    ("つぎの かどを みぎに まがってください。","tsugi no kado o migi ni magatte kudasai","Turn right at the next corner."),
    ("えきは ちかいですか。","eki wa chikai desu ka","Is the station near?")],
 },
 {
  "id": "restaurant", "order": 22, "title": "At the Restaurant", "icon": "🍜",
  "difficulty": 3,
  "description": "Order a meal, ask for the menu, and pay at a Japanese restaurant.",
  "objectives": ["Order with 〜を おねがいします","Ask for the menu/bill","Use a counter for orders"],
  "study_guide": [
    {"heading":"Ordering politely","body":"ラーメンを おねがいします = ramen, please. おねがいします is slightly more formal/polite than ください and great in restaurants."},
    {"heading":"Getting started","body":"メニューを ください = menu please. すみません calls the staff over. おすすめは なんですか = what do you recommend?"},
    {"heading":"Paying","body":"おかいけい おねがいします = the bill, please. べつべつで = separately (split the bill)."}],
  "examples": [
    ("メニューを ください。","menyuu o kudasai","Menu, please."),
    ("ラーメンを おねがいします。","raamen o onegai shimasu","Ramen, please."),
    ("おすすめは なんですか。","osusume wa nan desu ka","What do you recommend?"),
    ("おかいけい おねがいします。","okaikei onegai shimasu","Check, please.")],
  "grammar_note": {"title":"〜を おねがいします","body":"A polite request for service/items. すみません gets attention. counters: ひとつ/ふたつ for dishes."},
  "culture_note":"No tipping in Japan — service is included and tipping can confuse staff. Say ごちそうさまでした when leaving; it thanks the cooks and is good manners.",
  "vocab": [
    ("メニュー","メニュー","menyuu","menu"),
    ("お願いします","おねがいします","onegai shimasu","please (request)"),
    ("お勧め","おすすめ","osusume","recommendation"),
    ("お会計","おかいけい","okaikei","the bill / check"),
    ("注文","ちゅうもん","chuumon","order"),
    ("ラーメン","ラーメン","raamen","ramen"),
    ("定食","ていしょく","teishoku","set meal"),
    ("飲み放題","のみほうだい","nomihoudai","all-you-can-drink"),
    ("美味しい","おいしい","oishii","delicious"),
    ("お腹空いた","おなかすいた","onaka suita","I'm hungry")],
  "sentences": [
    ("メニューを ください。","menyuu o kudasai","Menu, please."),
    ("ラーメンを おねがいします。","raamen o onegai shimasu","Ramen, please."),
    ("おかいけい おねがいします。","okaikei onegai shimasu","The bill, please.")],
 },
 {
  "id": "can_dekiru", "order": 23, "title": "Ability (できます)", "icon": "💪",
  "difficulty": 3,
  "description": "Say what you can and can't do with できます and counters of skill.",
  "objectives": ["Use 〜が できます (can do)","Say noun + が できます","Combine with frequency words"],
  "study_guide": [
    {"heading":"〜が できます","body":"できます = can do / is possible. にほんごが できます = I can speak Japanese. The ability's object takes が."},
    {"heading":"Activity + が できます","body":"うんてんが できます = I can drive. りょうりが できます = I can cook. Pair a noun-activity with が できます."},
    {"heading":"Frequency words","body":"いつも (always), よく (often), ときどき (sometimes), あまり (not much), ぜんぜん (not at all) add nuance to ability/habit."}],
  "examples": [
    ("にほんごが すこし できます。","nihongo ga sukoshi dekimasu","I can speak a little Japanese."),
    ("うんてんが できますか。","unten ga dekimasu ka","Can you drive?"),
    ("よく りょうりを します。","yoku ryouri o shimasu","I often cook."),
    ("ぜんぜん およげません。","zenzen oyogemasen","I can't swim at all.")],
  "grammar_note": {"title":"〜が できます + frequency","body":"Noun + が できます = able to do. Negative できません. Frequency adverbs (いつも/よく/ときどき/あまり/ぜんぜん) modify verbs."},
  "culture_note":"Modesty is valued: even fluent speakers often say にほんごが すこし できます ('a little'). Downplaying ability is polite, not dishonest.",
  "vocab": [
    ("出来ます","できます","dekimasu","can do / is able"),
    ("運転","うんてん","unten","driving"),
    ("少し","すこし","sukoshi","a little"),
    ("いつも","いつも","itsumo","always"),
    ("よく","よく","yoku","often / well"),
    ("時々","ときどき","tokidoki","sometimes"),
    ("あまり","あまり","amari","not much (+neg)"),
    ("全然","ぜんぜん","zenzen","not at all (+neg)"),
    ("泳ぎます","およぎます","oyogimasu","to swim"),
    ("歌います","うたいます","utaimasu","to sing")],
  "sentences": [
    ("にほんごが できます。","nihongo ga dekimasu","I can speak Japanese."),
    ("よく りょうりを します。","yoku ryouri o shimasu","I often cook."),
    ("ぜんぜん およげません。","zenzen oyogemasen","I can't swim at all.")],
 },
 {
  "id": "comparisons", "order": 24, "title": "Comparing Things", "icon": "⚖️",
  "difficulty": 3,
  "description": "Compare two things and pick favorites with 〜より and いちばん.",
  "objectives": ["Compare with A は B より (A is more than B)","Ask どちらが ~ ですか","Use いちばん (the most)"],
  "study_guide": [
    {"heading":"A は B より 〜","body":"しんかんせんは くるまより はやいです = The bullet train is faster than a car. より = 'than'."},
    {"heading":"Asking which","body":"コーヒーと おちゃと どちらが すきですか = Which do you prefer, coffee or tea? どちら = which (of two)."},
    {"heading":"いちばん = the most","body":"なつが いちばん すきです = I like summer best. いちばん makes the superlative."}],
  "examples": [
    ("でんしゃは バスより はやいです。","densha wa basu yori hayai desu","The train is faster than the bus."),
    ("どちらが いいですか。","dochira ga ii desu ka","Which is better?"),
    ("なつが いちばん すきです。","natsu ga ichiban suki desu","I like summer the best."),
    ("これが いちばん やすいです。","kore ga ichiban yasui desu","This is the cheapest.")],
  "grammar_note": {"title":"より / どちら / いちばん","body":"A は B より [adj] = A is more [adj] than B. どちらが…ですか asks which of two. いちばん = most/best."},
  "culture_note":"When asked to choose, Japanese speakers may answer どちらでも いいです ('either is fine') to avoid imposing — a politeness reflex worth recognizing.",
  "vocab": [
    ("より","より","yori","than"),
    ("一番","いちばん","ichiban","most / best / number one"),
    ("どちら","どちら","dochira","which (of two)"),
    ("速い","はやい","hayai","fast"),
    ("遅い","おそい","osoi","slow / late"),
    ("電車","でんしゃ","densha","train"),
    ("バス","バス","basu","bus"),
    ("新幹線","しんかんせん","shinkansen","bullet train"),
    ("方","ほう","hou","side / direction (for comparison)"),
    ("同じ","おなじ","onaji","same")],
  "sentences": [
    ("でんしゃは バスより はやいです。","densha wa basu yori hayai desu","The train is faster than the bus."),
    ("なつが いちばん すきです。","natsu ga ichiban suki desu","I like summer best."),
    ("これが いちばん やすいです。","kore ga ichiban yasui desu","This is the cheapest.")],
 },
 {
  "id": "plans_future", "order": 25, "title": "Making Plans", "icon": "📅",
  "difficulty": 3,
  "description": "Talk about future plans, invitations, and 'let's ~' with 〜ましょう.",
  "objectives": ["Suggest with 〜ましょう (let's)","Use つもり (intend to)","Talk about tomorrow/next week"],
  "study_guide": [
    {"heading":"〜ましょう = let's","body":"いきましょう = let's go. たべましょう = let's eat. A warm, inclusive suggestion. 〜ましょうか offers ('shall I/we?')."},
    {"heading":"Plans with つもり","body":"あした べんきょうする つもりです = I intend to study tomorrow. つもり expresses intention."},
    {"heading":"Future time words","body":"あした (tomorrow), らいしゅう (next week), らいげつ (next month), らいねん (next year)."}],
  "examples": [
    ("いっしょに いきましょう。","issho ni ikimashou","Let's go together."),
    ("あした なにを しますか。","ashita nani o shimasu ka","What will you do tomorrow?"),
    ("らいしゅう りょこうする つもりです。","raishuu ryokou suru tsumori desu","I plan to travel next week."),
    ("てつだいましょうか。","tetsudaimashou ka","Shall I help you?")],
  "grammar_note": {"title":"〜ましょう / つもり","body":"Verb stem + ましょう = let's; + ましょうか = shall we/I. Dictionary verb + つもりです = intend to. Future uses present tense + time word."},
  "culture_note":"Plans are often confirmed politely and may stay flexible until the last moment. よろしく おねがいします seals an agreement to do something together.",
  "vocab": [
    ("明日","あした","ashita","tomorrow"),
    ("来週","らいしゅう","raishuu","next week"),
    ("来月","らいげつ","raigetsu","next month"),
    ("来年","らいねん","rainen","next year"),
    ("予定","よてい","yotei","plan / schedule"),
    ("つもり","つもり","tsumori","intention"),
    ("手伝います","てつだいます","tetsudaimasu","to help"),
    ("約束","やくそく","yakusoku","promise / appointment"),
    ("パーティー","パーティー","paatii","party"),
    ("週末","しゅうまつ","shuumatsu","weekend")],
  "sentences": [
    ("いっしょに いきましょう。","issho ni ikimashou","Let's go together."),
    ("あした べんきょうする つもりです。","ashita benkyou suru tsumori desu","I intend to study tomorrow."),
    ("てつだいましょうか。","tetsudaimashou ka","Shall I help?")],
 },

]
